namespace OwaspForge.Core;

public sealed class ChallengeRegistry
{
    private static readonly IReadOnlyList<ChallengeDefinition> Definitions =
    [
        Create("sql-injection", "SQL Injection", "A03: Injection", "Einfach", "25 Min.", 160,
            "Du erkennst, warum Daten nie in SQL-Text zusammengesetzt werden dürfen.",
            "Die historische Demo markiert String-Verkettung als intentionally vulnerable. Die sichere Variante trennt Abfragecode und Werte durch Parameter.",
            "Wähle die Massnahme, die eine lokale Suchabfrage sicher macht.", "Angreifende könnten lokale Beispieldaten ausserhalb der vorgesehenen Suche sehen.",
            "Die Suche behandelt Eingaben nur als Wert und liefert keine unerwarteten Datensätze.", "https://owasp.org/www-community/attacks/SQL_Injection", "Parameter haben Typ und Wert getrennt vom SQL-Code.", "Auch Validierung ersetzt keine parametrisierte Abfrage.",
            ("concat", "Eingabe vor dem SQL-Text escapen", "Escaping ist kontextabhängig und ersetzt keine Parameter."), ("parameter", "Parametrisierte Abfrage mit gebundenem Wert", ""), ("filter", "Nur Sonderzeichen sperren", "Eine Blocklist ist keine zuverlässige SQL-Abwehr.")),
        Create("xss", "Cross-Site Scripting", "A03: Injection", "Einfach", "20 Min.", 160,
            "Du verstehst, dass Ausgaben kontextgerecht encodiert werden müssen.",
            "Die historische Anzeige ist intentionally vulnerable, weil sie Text als HTML interpretiert. Die sichere Ansicht behandelt Beiträge als Text.",
            "Wähle die sichere Ausgabe für einen lokalen Kommentar.", "Fremder Code könnte im Browserkontext der Lernseite laufen.",
            "Der Kommentar erscheint als Text; Markup wird nicht ausgeführt.", "https://owasp.org/www-community/attacks/xss/", "Razor encodiert normale Textausgaben automatisch.", "Verwende keine HTML-Roh-Ausgabe für Benutzereingaben.",
            ("raw", "Text als HTML-Rohinhalt ausgeben", "Rohes HTML kann als Markup oder Script interpretiert werden."), ("encode", "Kontextgerecht HTML-encodieren", ""), ("client", "Nur im Browser filtern", "Die Ausgabe muss serverseitig sicher sein.")),
        Create("file-upload", "Unsicherer Datei-Upload", "A04: Insecure Design", "Mittel", "25 Min.", 160,
            "Du validierst Typ, Grösse und Dateiname und speicherst ausserhalb statischer Inhalte.",
            "Die historische Upload-Variante ist intentionally vulnerable, weil sie Namen und Pfad direkt übernimmt. Die sichere Variante speichert nur erlaubte, kleine Dateien ausserhalb des Webroots.",
            "Wähle die sichere lokale Upload-Regel.", "Unerwartete Dateien könnten zugänglich werden oder Speicher erschöpfen.",
            "Nur erlaubte, begrenzte Dateien werden unter einem serverseitigen Namen ausserhalb des Webroots gespeichert; sie werden nie ausgeführt.", "https://owasp.org/www-community/vulnerabilities/Unrestricted_File_Upload", "Dateiendungen allein beweisen keinen Inhaltstyp.", "Verwende eine Allowlist, Grössenlimit und einen generierten Namen.",
            ("extension", "Nur die Dateiendung prüfen und im Webroot speichern", "Endungen sind manipulierbar; der Webroot ist kein sicherer Speicherort."), ("upload-policy", "Allowlist, Grössenlimit, generierter Name, Speicher ausserhalb Webroot", ""), ("rename", "Die hochgeladene Datei nur umbenennen", "Ein neuer Name ersetzt keine Inhalts- und Grössenprüfung.")),
        Create("authentication", "Unsichere Authentifizierung", "A07: Identification and Authentication Failures", "Mittel", "30 Min.", 160,
            "Du kombinierst Passwort-Hashing, Session-Prüfung und Rate Limits.",
            "Die historische Login-Logik ist intentionally vulnerable: sie vergleicht einen Demo-String direkt. Die sichere Variante verwendet einen Passwort-Hasher, serverseitige Session-Prüfung und Limits für Fehlversuche.",
            "Wähle das vollständige lokale Schutzpaket.", "Konten könnten durch triviale Prüfungen oder viele Versuche gefährdet sein.",
            "Passwörter werden nie im Klartext gespeichert, Sitzungen werden serverseitig geprüft und Fehlversuche begrenzt.", "https://owasp.org/Top10/A07_2021-Identification_and_Authentication_Failures/", "Ein Hash ist kein Verschlüsselungsschlüssel.", "Rate Limits ergänzen, aber ersetzen keine sichere Passwortspeicherung.",
            ("plain", "Passwort direkt vergleichen und im Speicher behalten", "Klartextpasswörter und direkte Vergleiche schützen nicht."), ("secure-auth", "Hashing, serverseitige Session-Prüfung und Rate Limit", ""), ("captcha", "Nur ein Captcha hinzufügen", "Ein Captcha allein ist kein vollständiges Authentifizierungskonzept.")),
        Create("session-csrf", "Sitzungen und CSRF", "A07: Identification and Authentication Failures", "Mittel", "25 Min.", 160,
            "Du schützt angemeldete lokale Aktionen gegen Sessiondiebstahl und fremde Formularanfragen.",
            "Eine dauerhaft gültige Session-ID oder ein Formular ohne Anti-Forgery-Prüfung wäre intentionally vulnerable. Die Plattform verwendet sichere Cookies und serverseitig geprüfte Anti-Forgery-Tokens.",
            "Wähle den Schutz für eine lokale Kontoänderung.", "Eine fremde Seite könnte sonst im Kontext einer angemeldeten Demoperson eine Aktion auslösen.",
            "Die Aktion verlangt eine gültige Session, ein Anti-Forgery-Token und sichere Cookie-Attribute.", "https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html", "CSRF-Schutz ergänzt Authentifizierung; er ersetzt sie nicht.", "Cookies brauchen mindestens Secure, HttpOnly und passende SameSite-Regeln.",
            ("client-token", "Token nur im Browser vergleichen", "Der Server muss den Token prüfen."), ("csrf-session", "Serverseitiger Anti-Forgery-Check mit sicherem Session-Cookie", ""), ("referer", "Nur auf einen Referer-Header vertrauen", "Ein Header allein ist keine vollständige Schutzmassnahme.")),
        Create("idor", "Broken Access Control / IDOR", "A01: Broken Access Control", "Mittel", "30 Min.", 160,
            "Du prüfst Zugriffe auf jedes einzelne Objekt serverseitig.",
            "Die historische Demo vertraut auf eine Objekt-ID aus der URL und ist intentionally vulnerable. Die sichere Variante vergleicht Eigentümer und aktuelle Identität auf dem Server.",
            "Wähle die Prüfung vor dem Lesen eines lokalen Profils.", "Lokale Beispieldaten einer anderen Person wären sichtbar.",
            "Nur die berechtigte Demobenutzerin erhält ihr eigenes Profil; andere IDs ergeben eine Ablehnung.", "https://owasp.org/Top10/A01_2021-Broken_Access_Control/", "Eine ID ist kein Berechtigungsnachweis.", "Prüfe Besitz oder Rolle auf dem Server, nicht im Link.",
            ("hidden", "ID in einem versteckten Feld speichern", "Versteckte Felder können verändert werden."), ("owner", "Aktuelle Identität gegen Objektbesitz prüfen", ""), ("route", "Objekt-ID nur anders benennen", "Eine anders benannte ID ist keine Autorisierung.")),
        Create("ssrf", "SSRF-Grundlagen", "A10: Server-Side Request Forgery", "Mittel", "25 Min.", 160,
            "Du begrenzt serverseitige Abrufe auf explizite lokale Mock-Ziele.",
            "Die historische Abrufidee ist intentionally vulnerable, weil sie eine beliebige Adresse akzeptiert. OWASP Forge ruft nie eine vom Client angegebene URL auf: die sichere Demo arbeitet nur mit einer festen lokalen Mock-Kennung.",
            "Wähle die sichere Abrufregel.", "Ein Server könnte sonst interne oder externe Ziele im falschen Kontext anfragen.",
            "Nur eine registrierte Mock-Ressource wird verarbeitet; beliebige URLs werden abgelehnt und Container haben kein Netzwerk.", "https://owasp.org/Top10/A10_2021-Server-Side_Request_Forgery_%28SSRF%29/", "Eine Blocklist kann unbekannte Ziele übersehen.", "Nimm eine feste Allowlist von Namen, nicht URLs vom Client.",
            ("blocklist", "Einige Hostnamen auf einer Blocklist ablehnen", "Blocklists übersehen unbekannte Ziele."), ("allowlist", "Nur feste lokale Mock-Kennungen aus einer Allowlist akzeptieren", ""), ("redirect", "Weiterleitungen erst nach dem Abruf prüfen", "Der erste Abruf wäre bereits frei wählbar.")),
        Create("cryptography-secrets", "Kryptografie und Geheimnisse", "A02: Cryptographic Failures", "Mittel", "30 Min.", 160,
            "Du schützt lokale Beispieldaten durch passende Verschlüsselung und trennst Schlüssel vom Quellcode.",
            "Ein fest im Repository eingetragener Schlüssel oder eine selbst erfundene Verschlüsselung wäre intentionally vulnerable. Die Station betrachtet nur Platzhalterdaten und keine echten Geheimnisse.",
            "Wähle die Regel für ein lokales Schutzgeheimnis.", "Fest eingetragene Schlüssel können mit dem Code kopiert werden; ungeschützte Daten wären bei Verlust lesbar.",
            "Schlüssel stammen aus sicherer lokaler Konfiguration, Daten nutzen erprobte Kryptografie und Geheimnisse erscheinen nie in Logs.", "https://cheatsheetseries.owasp.org/cheatsheets/Cryptographic_Storage_Cheat_Sheet.html", "Verschlüsselung schützt Daten nicht ohne einen geschützten Schlüssel.", "Passwörter werden gehasht, nicht entschlüsselbar verschlüsselt.",
            ("hardcode", "Schlüssel direkt im Quellcode hinterlegen", "Repository und Build-Ausgaben würden das Geheimnis verbreiten."), ("secret-store", "Erprobte Kryptografie und getrennte lokale Schlüsselverwaltung nutzen", ""), ("custom", "Eine eigene Verschlüsselung erfinden", "Eigene Kryptografie ist kaum zuverlässig prüfbar.")),
        Create("security-misconfiguration", "Sicherheitskonfiguration", "A05: Security Misconfiguration", "Einfach", "25 Min.", 160,
            "Du erkennst sichere Standardwerte für Fehler, HTTP-Header und lokale Bereitstellung.",
            "Ein Debug-Stacktrace für Besuchende oder eine offene Bindung wäre intentionally vulnerable. OWASP Forge zeigt keine Stacktraces in der Oberfläche und bindet Dienste nur an localhost.",
            "Wähle die sichere Standardkonfiguration.", "Fehlerdetails oder unnötig offene Dienste könnten interne Informationen preisgeben.",
            "Produktionsähnliche lokale Einstellungen liefern neutrale Fehlerseiten, Schutz-Header und eine localhost-Bindung.", "https://owasp.org/Top10/A05_2021-Security_Misconfiguration/", "Sichere Defaults müssen bewusst geprüft werden.", "Debug-Ausgaben gehören in geschützte lokale Logs, nicht in die Benutzeroberfläche.",
            ("debug", "Stacktraces und Debugmodus für alle anzeigen", "Stacktraces können interne Implementierungsdetails verraten."), ("secure-default", "Neutrale Fehlerseiten, Schutz-Header und localhost-Bindung", ""), ("hide", "Nur die Fehlermeldung im Browser verstecken", "Die Serverkonfiguration muss selbst sicher sein.")),
        Create("dependencies-sbom", "Abhängigkeiten und SBOM", "A06: Vulnerable and Outdated Components", "Einfach", "20 Min.", 160,
            "Du hältst Komponenten nachvollziehbar, aktuell und auf bekannte Schwachstellen geprüft.",
            "Eine unüberblickte Bibliothek ohne Versionspflege wäre intentionally vulnerable. Diese Station führt keine externen Scans aus, sondern lehrt lokale Inventarisierung und Updates.",
            "Wähle den sicheren Umgang mit einer Projektabhängigkeit.", "Bekannte Schwachstellen in Komponenten können die gesamte Anwendung betreffen.",
            "Abhängigkeiten sind inventarisiert, auf Schwachstellen geprüft und kontrolliert aktualisiert.", "https://owasp.org/Top10/A06_2021-Vulnerable_and_Outdated_Components/", "Eine SBOM macht Komponenten sichtbar, ersetzt aber keine Pflege.", "Updates sollen getestet und nachvollziehbar erfolgen.",
            ("ignore", "Versionen ohne Inventar unverändert lassen", "Unbekannte Komponenten lassen sich nicht zuverlässig beurteilen."), ("inventory", "SBOM pflegen, Hinweise prüfen und Updates testen", ""), ("latest", "Jede Version automatisch ohne Test übernehmen", "Ungetestete Updates können eigene Risiken erzeugen.")),
        Create("supply-chain-integrity", "Integrität der Lieferkette", "A08: Software and Data Integrity Failures", "Mittel", "25 Min.", 160,
            "Du prüfst, woher Artefakte stammen und wie Build- und Freigabeprozesse geschützt sind.",
            "Ein ungeprüftes Paket oder ein Artefakt aus unbekannter Quelle wäre intentionally vulnerable. Die Lernstation arbeitet nur mit lokalen Beispielen und führt keine Fremdartefakte aus.",
            "Wähle die Kontrolle vor einer lokalen Freigabe.", "Manipulierte Artefakte oder Daten könnten unbemerkt in eine Anwendung gelangen.",
            "Die Herkunft ist nachvollziehbar, Integrität wird geprüft und der Build erzeugt reproduzierbare Artefakte.", "https://owasp.org/Top10/A08_2021-Software_and_Data_Integrity_Failures/", "Vertrauen in eine Quelle braucht überprüfbare Herkunft.", "Eine Integritätsprüfung muss vor der Verwendung stattfinden.",
            ("trust", "Ein Artefakt wegen seines Namens vertrauen", "Namen belegen weder Herkunft noch Integrität."), ("verify", "Herkunft, Signatur oder Hash vor Verwendung prüfen", ""), ("after", "Integrität erst nach der Ausführung prüfen", "Dann wäre die Vertrauensgrenze bereits überschritten.")),
        Create("logging-monitoring", "Logging und Monitoring", "A09: Security Logging and Monitoring Failures", "Einfach", "20 Min.", 160,
            "Du protokollierst sicherheitsrelevante Ereignisse ohne Geheimnisse und machst Auffälligkeiten nachvollziehbar.",
            "Gar keine Login-Fehler zu erfassen oder Passwörter mitzuloggen wäre intentionally vulnerable. Die Plattform protokolliert strukturiert und ohne geheime Werte.",
            "Wähle die sichere Protokollierungsregel.", "Ohne brauchbare Ereignisse bleiben Missbrauch und Fehler unbemerkt; Geheimnisse in Logs vergrössern den Schaden.",
            "Ereignisse enthalten Kontext und Zeit, aber keine Passwörter, Tokens oder vollständigen sensiblen Inhalte.", "https://owasp.org/Top10/A09_2021-Security_Logging_and_Monitoring_Failures/", "Ein Logeintrag soll bei einer Untersuchung helfen, ohne Geheimnisse zu verraten.", "Strukturierte Felder sind besser auswertbar als zusammengesetzte Textlogs.",
            ("secrets", "Passwörter und Tokens zur Diagnose protokollieren", "Geheimnisse gehören niemals in Logs."), ("structured", "Sicherheitsereignisse strukturiert und ohne Geheimnisse erfassen", ""), ("none", "Fehlgeschlagene Aktionen gar nicht erfassen", "Ohne Ereignisse bleiben Auffälligkeiten unsichtbar."))
    ];

    public IReadOnlyList<ChallengeDefinition> All => Definitions;

    public ChallengeDefinition? Find(string id) => Definitions.SingleOrDefault(challenge => StringComparer.Ordinal.Equals(challenge.Id, id));

    private static ChallengeDefinition Create(string id, string title, string category, string difficulty, string duration, int points, string goal, string explanation, string task, string impact, string expected, string url, string hintOne, string hintTwo, params (string Value, string Label, string Feedback)[] options) =>
        new(id, title, category, difficulty, duration, points, goal, explanation, task, impact, expected, url, [hintOne, hintTwo], options.Select(option => new ChallengeOption(option.Value, option.Label, option.Feedback)).ToArray(), options[1].Value)
        {
            Course = CourseName(id),
            Questions = QuestionSet(id, task),
            SolutionExplanation = SolutionText(id)
        };

    private static string CourseName(string id) => id switch
    {
        "sql-injection" or "xss" or "file-upload" => "Eingabe und Ausgabe",
        "authentication" or "session-csrf" or "idor" => "Identität und Zugriffe",
        "ssrf" or "cryptography-secrets" or "security-misconfiguration" => "Sichere Architektur",
        _ => "Betrieb und Lieferkette"
    };

    private static IReadOnlyList<ChallengeQuestion> QuestionSet(string id, string task) => id switch
    {
        "sql-injection" => Six(task, ("parameter", "Parametrisierte Abfrage mit gebundenem Wert", "concat", "SQL-Text durch String-Verkettung bauen", "filter", "Nur Sonderzeichen sperren"),
            ("parameter", "SQL-Code und Wert durch einen gebundenen Parameter trennen", "concat", "Wert direkt in den SQL-String einsetzen", "filter", "Eine kurze Blocklist verwenden"),
            ("parameter", "Die Abfrage mit einem Parameter ausführen", "filter", "Nur verdächtige Zeichen ablehnen", "concat", "Die Eingabe in SQL-Text einfügen"),
            ("parameter", "Auch bei Zahlen und IDs Parameter verwenden", "concat", "Zahlen direkt in SQL einfügen", "filter", "IDs nur im Browser prüfen"),
            ("parameter", "Datenbankrechte auf das notwendige Minimum begrenzen", "concat", "Der App-Datenbank volle Rechte geben", "filter", "Rechte nur in der Dokumentation erwähnen"),
            ("parameter", "Datenzugriff mit erwarteten Typen und Parametern testen", "concat", "Nur die Darstellung im Browser testen", "filter", "Auf einen einzelnen Beispielwert vertrauen")),
        "xss" => Six(task, ("encode", "Kontextgerecht HTML-encodieren", "raw", "Text als HTML-Rohinhalt ausgeben", "client", "Nur im Browser filtern"),
            ("encode", "Als Text mit passendem Output-Encoding rendern", "raw", "Als ungeprüftes HTML rendern", "client", "Erst nach dem Rendern filtern"),
            ("encode", "Roh-HTML für Benutzereingaben vermeiden", "client", "Eine Client-Filterung voraussetzen", "raw", "Die Eingabe mit Html.Raw ausgeben"),
            ("encode", "Für Attribute ein passendes Attribut-Encoding nutzen", "raw", "Text direkt in ein HTML-Attribut setzen", "client", "Nur sichtbare Zeichen entfernen"),
            ("encode", "URLs vor Verwendung auf erlaubte Schemas und Ziele prüfen", "raw", "Eine Benutzereingabe direkt als Linkziel verwenden", "client", "Nur den Linktext encodieren"),
            ("encode", "Eine Content-Security-Policy als zusätzliche Schutzschicht einsetzen", "raw", "Auf eine CSP verzichten", "client", "Nur ein Browser-Plugin erwarten")),
        "file-upload" => Six(task, ("upload-policy", "Allowlist, Grössenlimit, generierter Name, ausserhalb des Webroots", "extension", "Nur die Endung prüfen und im Webroot speichern", "rename", "Die Datei nur umbenennen"),
            ("upload-policy", "Typ, Grösse, Name und Speicherort serverseitig prüfen", "rename", "Nur einen neuen Dateinamen vergeben", "extension", "Nur die Endung prüfen"),
            ("upload-policy", "Unter generiertem Namen ausserhalb des Webroots speichern", "extension", "Im öffentlichen Webroot speichern", "rename", "Im Webroot umbenennen"),
            ("upload-policy", "Die maximale Dateigrösse vor dem Speichern erzwingen", "extension", "Nur die Dateiendung lesen", "rename", "Nur einen längeren Namen verwenden"),
            ("upload-policy", "Den ermittelten Inhaltstyp gegen eine Allowlist prüfen", "extension", "Den vom Browser gemeldeten Typ übernehmen", "rename", "Den Dateinamen als Typnachweis nutzen"),
            ("upload-policy", "Uploads nie als ausführbaren Inhalt bereitstellen", "extension", "Uploads direkt über ihre Original-URL ausliefern", "rename", "Nur die Originalendung verstecken")),
        "authentication" => Six(task, ("secure-auth", "Hashing, serverseitige Session-Prüfung und Rate Limit kombinieren", "plain", "Passwort direkt vergleichen", "captcha", "Nur ein Captcha hinzufügen"),
            ("secure-auth", "Passwort-Hash, serverseitige Session und Limit verwenden", "captcha", "Nur ein Captcha anzeigen", "plain", "Das Passwort im Klartext vergleichen"),
            ("secure-auth", "Ein serverseitiges Rate Limit ergänzen", "plain", "Weitere Klartextvergleiche erlauben", "captcha", "Das Limit nur im Browser anzeigen"),
            ("secure-auth", "Einen etablierten Passwort-Hasher mit Salt verwenden", "plain", "Passwörter reversibel verschlüsseln", "captcha", "Passwörter in Logs vergleichen"),
            ("secure-auth", "Nach Login die Session-ID erneuern", "plain", "Die bestehende Session-ID weiterverwenden", "captcha", "Nur die Login-Seite neu laden"),
            ("secure-auth", "Kontowiederherstellung mit zeitlich begrenzten Einmal-Token gestalten", "plain", "Ein dauerhaftes Wiederherstellungskennwort senden", "captcha", "Den Token in die URL-Logs schreiben")),
        "session-csrf" => Six(task, ("csrf-session", "Serverseitiger Anti-Forgery-Check mit sicherem Session-Cookie", "client-token", "Token nur im Browser vergleichen", "referer", "Nur auf einen Referer-Header vertrauen"),
            ("csrf-session", "Einen Anti-Forgery-Token bei jeder zustandsändernden Anfrage prüfen", "client-token", "Nur eine JavaScript-Variable prüfen", "referer", "Den Token optional machen"),
            ("csrf-session", "Cookies mit HttpOnly, Secure und passendem SameSite setzen", "client-token", "Cookies für JavaScript lesbar machen", "referer", "Cookie-Attribute weglassen"),
            ("csrf-session", "Die Session nach Abmeldung serverseitig ungültig machen", "client-token", "Nur den Browser-Tab schliessen", "referer", "Das Cookie ohne Serverprüfung löschen"),
            ("csrf-session", "Sitzungen zeitlich begrenzen und bei Risiko neu prüfen", "client-token", "Sitzungen unbegrenzt gültig lassen", "referer", "Nur auf Seitenreload zählen"),
            ("csrf-session", "Zustandsänderungen nur mit POST und Schutzprüfung ausführen", "client-token", "Kontoänderungen über GET ausführen", "referer", "Den Schutz nur für sichtbare Formulare nutzen")),
        "idor" => Six(task, ("owner", "Aktuelle Identität gegen Objektbesitz prüfen", "hidden", "ID in einem versteckten Feld speichern", "route", "Objekt-ID nur anders benennen"),
            ("owner", "Besitz oder Rolle serverseitig vergleichen", "route", "Die Route anders benennen", "hidden", "Auf ein verstecktes Feld vertrauen"),
            ("owner", "Der Client darf die ID frei verändern", "hidden", "Versteckte Felder sind unsichtbar", "route", "Eine längere URL wäre sicherer"),
            ("owner", "Autorisierung bei jedem einzelnen Objektzugriff prüfen", "hidden", "Nur beim ersten Seitenaufruf prüfen", "route", "Nur die Navigation ausblenden"),
            ("owner", "Bei fehlender Berechtigung serverseitig ablehnen", "hidden", "Das Objekt nur optisch verstecken", "route", "Die Objekt-ID verschleiern"),
            ("owner", "Tests für erlaubte und verbotene Objektzugriffe schreiben", "hidden", "Nur den Happy Path testen", "route", "Nur URLs manuell umbenennen")),
        "ssrf" => Six(task, ("allowlist", "Nur feste lokale Mock-Kennungen aus einer Allowlist akzeptieren", "blocklist", "Einige Hostnamen blockieren", "redirect", "Weiterleitungen erst nach dem Abruf prüfen"),
            ("allowlist", "Eine feste Kennungs-Allowlist ohne Client-URL verwenden", "redirect", "Die Antwort nach einer beliebigen Anfrage prüfen", "blocklist", "Nur bekannte Hostnamen sperren"),
            ("allowlist", "Es gibt keinen frei wählbaren Netzwerkausgang", "blocklist", "Unbekannte Ziele bleiben trotzdem möglich", "redirect", "Der erste Abruf findet bereits statt"),
            ("allowlist", "Nur serverseitig konfigurierte Ziele auflösen", "blocklist", "Client-URLs in Host und Pfad zerlegen", "redirect", "Weiterleitungen automatisch folgen"),
            ("allowlist", "Container ohne ausgehendes Netzwerk betreiben", "blocklist", "Das Netzwerk für spätere Flexibilität öffnen", "redirect", "Nur den Browser einschränken"),
            ("allowlist", "Abrufversuche mit sicherem Kontext protokollieren", "blocklist", "Komplette Geheimnisse in Logs speichern", "redirect", "Fehlversuche nie erfassen")),
        "cryptography-secrets" => Six(task, ("secret-store", "Erprobte Kryptografie und getrennte lokale Schlüsselverwaltung nutzen", "hardcode", "Schlüssel direkt im Quellcode hinterlegen", "custom", "Eine eigene Verschlüsselung erfinden"),
            ("secret-store", "Passwörter mit einem modernen Passwort-Hasher speichern", "hardcode", "Passwörter entschlüsselbar speichern", "custom", "Passwörter selbst verschlüsseln"),
            ("secret-store", "Schlüssel aus lokaler Konfiguration ausserhalb des Repositories laden", "hardcode", "Schlüssel in appsettings.json committen", "custom", "Schlüssel im Frontend hinterlegen"),
            ("secret-store", "Nur notwendige Daten verschlüsseln und klar klassifizieren", "hardcode", "Alle Daten ohne Priorisierung verschleiern", "custom", "Kryptografie ohne Datenmodell wählen"),
            ("secret-store", "Geheimnisse aus Fehlermeldungen und Logs ausschliessen", "hardcode", "Geheimnisse zur Diagnose ausgeben", "custom", "Tokens im Client speichern"),
            ("secret-store", "Erprobte Bibliotheken und sichere Standardalgorithmen verwenden", "hardcode", "Eigene Algorithmen schreiben", "custom", "Veraltete Beispiele kopieren")),
        "security-misconfiguration" => Six(task, ("secure-default", "Neutrale Fehlerseiten, Schutz-Header und localhost-Bindung", "debug", "Stacktraces und Debugmodus für alle anzeigen", "hide", "Nur die Fehlermeldung im Browser verstecken"),
            ("secure-default", "Stacktraces nur in geschützten lokalen Logs erfassen", "debug", "Stacktraces an Besuchende senden", "hide", "Serverfehler ignorieren"),
            ("secure-default", "Dienste nur an localhost binden", "debug", "An allen Netzwerkinterfaces lauschen", "hide", "Die Portnummer geheim halten"),
            ("secure-default", "Sichere HTTP-Antwortheader zentral setzen", "debug", "Header nur pro einzelner Seite setzen", "hide", "Ohne Header auf Browser hoffen"),
            ("secure-default", "Debug- und Testendpunkte in der Freigabe entfernen", "debug", "Debug-Endpunkte versteckt lassen", "hide", "Nur den Link aus dem Menü nehmen"),
            ("secure-default", "Konfiguration im Review und automatisiert prüfen", "debug", "Konfiguration nur einmal festlegen", "hide", "Sichere Defaults nicht dokumentieren")),
        "dependencies-sbom" => Six(task, ("inventory", "SBOM pflegen, Hinweise prüfen und Updates testen", "ignore", "Versionen ohne Inventar unverändert lassen", "latest", "Jede Version automatisch ohne Test übernehmen"),
            ("inventory", "Komponenten, Versionen und Herkunft inventarisieren", "ignore", "Nur direkte Pakete notieren", "latest", "Erst nach einem Vorfall suchen"),
            ("inventory", "Bekannte Schwachstellen vor einem Update bewerten", "ignore", "Warnungen grundsätzlich ignorieren", "latest", "Patches ohne Test sofort veröffentlichen"),
            ("inventory", "Updates in einer lokalen Testumgebung prüfen", "ignore", "Abhängigkeiten nie aktualisieren", "latest", "Nur im Produktionsbetrieb testen"),
            ("inventory", "Nicht mehr benötigte Abhängigkeiten entfernen", "ignore", "Unbenutzte Pakete behalten", "latest", "Mehr Pakete für alle Fälle installieren"),
            ("inventory", "Den Abhängigkeitsstand nachvollziehbar dokumentieren", "ignore", "Versionen nur im Gedächtnis behalten", "latest", "Lock-Dateien ohne Prüfung ändern")),
        "supply-chain-integrity" => Six(task, ("verify", "Herkunft, Signatur oder Hash vor Verwendung prüfen", "trust", "Ein Artefakt wegen seines Namens vertrauen", "after", "Integrität erst nach der Ausführung prüfen"),
            ("verify", "Artefakte aus bekannten Quellen nachvollziehbar beziehen", "trust", "Dateien aus beliebigen Quellen laden", "after", "Herkunft später dokumentieren"),
            ("verify", "Build-Artefakte reproduzierbar erzeugen", "trust", "Lokale Handarbeit nicht dokumentieren", "after", "Nur das Endergebnis speichern"),
            ("verify", "Freigaberechte auf wenige verantwortliche Konten begrenzen", "trust", "Allen Build-Zugriff geben", "after", "Freigaben ohne Audit erlauben"),
            ("verify", "Automatisierte Prüfungen vor dem Veröffentlichen ausführen", "trust", "Prüfungen optional machen", "after", "Prüfungen erst nach Release starten"),
            ("verify", "Integritätsfehler stoppen und untersuchen", "trust", "Abweichungen als Zufall akzeptieren", "after", "Trotz Fehler weiterverteilen")),
        "logging-monitoring" => Six(task, ("structured", "Sicherheitsereignisse strukturiert und ohne Geheimnisse erfassen", "secrets", "Passwörter und Tokens zur Diagnose protokollieren", "none", "Fehlgeschlagene Aktionen gar nicht erfassen"),
            ("structured", "Zeit, Ereignistyp und sichere Kontextfelder erfassen", "secrets", "Vollständige Eingaben speichern", "none", "Nur unstrukturierte Zufallstexte schreiben"),
            ("structured", "Login-Fehlschläge ohne Passwortinhalt erfassen", "secrets", "Eingegebene Passwörter erfassen", "none", "Login-Fehler nicht protokollieren"),
            ("structured", "Logzugriff und Aufbewahrung gezielt schützen", "secrets", "Logs öffentlich verfügbar machen", "none", "Logs unbegrenzt ungeschützt speichern"),
            ("structured", "Auffällige Ereignisse überprüfbar alarmieren", "secrets", "Bei jedem Ereignis unpriorisiert alarmieren", "none", "Nie auf Muster reagieren"),
            ("structured", "Ereignisse für Diagnose und Nachvollziehbarkeit korrelierbar halten", "secrets", "Geheimnisse als Korrelationswert nutzen", "none", "Keine eindeutigen Ereigniskennungen verwenden")),
        _ => Six(task, ("secure", "Sichere serverseitige Prüfung", "unsafe", "Unsichere Variante", "unknown", "Unklare Variante"),
            ("secure", "Sichere serverseitige Prüfung", "unsafe", "Unsichere Variante", "unknown", "Unklare Variante"),
            ("secure", "Sichere serverseitige Prüfung", "unsafe", "Unsichere Variante", "unknown", "Unklare Variante"),
            ("secure", "Sichere serverseitige Prüfung", "unsafe", "Unsichere Variante", "unknown", "Unklare Variante"),
            ("secure", "Sichere serverseitige Prüfung", "unsafe", "Unsichere Variante", "unknown", "Unklare Variante"),
            ("secure", "Sichere serverseitige Prüfung", "unsafe", "Unsichere Variante", "unknown", "Unklare Variante"))
    };

    private static IReadOnlyList<ChallengeQuestion> Six(
        string task,
        (string SafeValue, string SafeLabel, string FirstValue, string FirstLabel, string SecondValue, string SecondLabel) one,
        (string SafeValue, string SafeLabel, string FirstValue, string FirstLabel, string SecondValue, string SecondLabel) two,
        (string SafeValue, string SafeLabel, string FirstValue, string FirstLabel, string SecondValue, string SecondLabel) three,
        (string SafeValue, string SafeLabel, string FirstValue, string FirstLabel, string SecondValue, string SecondLabel) four,
        (string SafeValue, string SafeLabel, string FirstValue, string FirstLabel, string SecondValue, string SecondLabel) five,
        (string SafeValue, string SafeLabel, string FirstValue, string FirstLabel, string SecondValue, string SecondLabel) six) =>
        [Question(task, one), Question("Welche weitere Schutzregel gehört zu dieser Station?", two), Question("Welche serverseitige Entscheidung ist hier wichtig?", three), Question("Wie wird die Regel konsequent umgesetzt?", four), Question("Welche zusätzliche Massnahme stärkt den Schutz?", five), Question("Wie überprüfst du die Schutzregel?", six)];

    private static ChallengeQuestion Question(string prompt, (string SafeValue, string SafeLabel, string FirstValue, string FirstLabel, string SecondValue, string SecondLabel) option) =>
        new(prompt, [new(option.FirstValue, option.FirstLabel, "Diese Variante schützt die Station nicht zuverlässig."), new(option.SafeValue, option.SafeLabel, string.Empty), new(option.SecondValue, option.SecondLabel, "Diese Massnahme reicht allein nicht aus.")], option.SafeValue);

    private static string SolutionText(string id) => id switch
    {
        "sql-injection" => "Parameter trennen SQL-Struktur und Eingabewert. Ergänzende Rechtebegrenzung und Tests reduzieren die Folgen von Fehlern zusätzlich.",
        "xss" => "Kontextgerechtes Encoding behandelt Beiträge als Text. Eine Content-Security-Policy ergänzt die sichere Ausgabe, ersetzt sie aber nicht.",
        "file-upload" => "Allowlist, Grössenlimit, Inhaltsprüfung und ein generierter Name begrenzen das Risiko. Speicherung ausserhalb des Webroots verhindert direkte Ausführung.",
        "authentication" => "Ein Passwort-Hash, serverseitige Session-Prüfung, Session-Erneuerung und Rate Limits schützen unterschiedliche Teile des Anmeldevorgangs gemeinsam.",
        "session-csrf" => "Sichere Cookie-Attribute, serverseitige Session-Invalidierung und Anti-Forgery-Prüfung schützen zustandsändernde Anfragen gemeinsam.",
        "idor" => "Der Server vergleicht Identität, Rolle und Objektbesitz bei jedem Objektzugriff. Eine URL-ID wird nie als Berechtigung akzeptiert.",
        "ssrf" => "Eine feste Mock-Allowlist verhindert, dass Eingaben einen Netzwerkpfad bestimmen. Container ohne ausgehendes Netzwerk bilden eine zweite Schutzgrenze.",
        "cryptography-secrets" => "Schlüssel bleiben ausserhalb des Quellcodes, Passwörter werden gehasht und erprobte Kryptografie schützt nur klar klassifizierte Daten.",
        "security-misconfiguration" => "Sichere Defaults bedeuten neutrale Fehlerseiten, zentrale Schutz-Header, localhost-Bindung und regelmässig geprüfte Konfiguration.",
        "dependencies-sbom" => "Ein Inventar schafft Transparenz. Hinweise werden bewertet, Änderungen getestet und nicht mehr benötigte Komponenten entfernt.",
        "supply-chain-integrity" => "Nachvollziehbare Herkunft, Integritätsprüfungen und kontrollierte Freigaben schützen die gesamte Build- und Lieferkette.",
        "logging-monitoring" => "Strukturierte, geschützte Logs machen Auffälligkeiten untersuchbar, ohne Passwörter, Tokens oder andere Geheimnisse preiszugeben.",
        _ => "Die Schutzregel wird serverseitig geprüft und lokal gespeichert."
    };
}
